ignored_config_entities:
  - core.extension
  - 'devel.*'
  - field_ui.settings
  - 'system.menu.*'
  - system.performance
  - system.site
  - 'user.role.*'
  - email_sign_up.setup
  - contact_info.setup
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
