address:
  country_name: US
  legal_name: ''
  street_address: ''
  street_address_2: ''
  locality: ''
  region: ''
  postal_code: ''
phone:
  country_code: ''
  number: ''
fax:
  number: ''
email:
  emailaddress: ihpifeedback@umich.edu
social_seo:
  site_twitter: ''
  site_google_plus: ''
