address:
  country_name: US
  legal_name: 'U-M Institute for Healthcare Policy & Innovation'
  street_address: '2800 Plymouth Road, North Campus Research Complex (NCRC)'
  street_address_2: 'Building 16'
  locality: 'Ann Arbor'
  region: MI
  postal_code: '48109'
phone:
  country_code: ''
  number: ''
fax:
  number: ''
social_seo:
  site_twitter: ''
  site_google_plus: ''
social:
  table:
    1:
      name: LinkedIn
      url: 'https://www.linkedin.com/company/institute-for-health-care-policy-and-innovation'
      enable: '1'
      weight: '10'
    2:
      name: Youtube
      url: 'https://www.youtube.com/playlist?list=PLNxqP-XbH8BLi5K_2giRk0NeJTLct7ybl'
      enable: '1'
      weight: '10'
    3:
      name: Twitter
      url: 'https://twitter.com/UM_IHPI'
      enable: '1'
      weight: '10'
