module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  background_image_formatter: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_font: 0
  color: 0
  color_field: 0
  comment: 0
  compro_content: 0
  compro_credit: 0
  compro_custom: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_update: 0
  contact: 0
  contact_info: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  email_sign_up: 0
  embed: 0
  entity: 0
  entity_embed: 0
  features: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  google_cse: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  libraries: 0
  link: 0
  linked_field: 0
  media: 0
  menu_trail_by_path: 0
  menu_ui: 0
  metatag: 0
  metatag_favicons: 0
  metatag_google_cse: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phoenix_component: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  responsive_image: 0
  scheduler: 0
  search: 0
  shortcut: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_infinite_scroll: 0
  webform: 0
  webform_jqueryui_buttons: 0
  webform_location_geocomplete: 0
  webform_node: 0
  webform_templates: 0
  xmlsitemap: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  compro_adminimal: 0
  compro_theme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
